### PR TITLE
fixed visual issues with spellcasting classes

### PR DESCRIPTION
**Pull request by Tranquwil**
Fixed width of the concentration check button for spell class 1 and 2.
Fixed the class of a column of +s for spell class 0.
Added missing border for spell class 2.

### CODE REVIEW

**Comment by vince-roll20** [comment]
Thanks Tranquwil

**Comment by vince-roll20** [comment]
Just had a quick look.  The Concentration Check might still have issues when the sheet is toggled into the compact mode...  
We can probably solve these inconsistencies by removing the inline min-width:16.4rem from the button and removing width:14.5rem from .sheet-spellcaster-button in the css.
image
and remove max-width:14.5rem to fix compact mode
image
That _seems_ to work.  The sheet has so many variables.  It's hard to make a change without it possibly effecting other areas.  A lesson I often re-learn. lol

**Comment by Tranquwil** [comment]
Good catch.
I also had to turn off max-width: 14.4rem !important and width: 14.4rem !important to see the change you showed.
image
.sheet-spellcaster-button is also used for the Casterlevel Check button, however these changes barely seem to affect it (just a few pixels of difference).
image
Other than that, I don't see any issues with your plan. You can go ahead and implement it.

**Comment by vince-roll20** [comment]
Ah.., I knew I saw **!important** was being used as well.  I must have disabled that initially while fooling around in the browser's inspector and forgot about it. ;-)
I'll try and get this worked in for Monday's pulls.
Thanks T

**Comment by vince-roll20** [comment]
Pull submitted
https://github.com/Roll20/roll20-character-sheets/pull/8247

**Pull request merged**
