### PR TITLE
Roll20 pathfinder character sheet master

### PR DESCRIPTION
**Pull request by vince-roll20**
fixes spells-notes attribute name and title text to match spell_options

### CODE REVIEW

**Comment by plutosdad** [comment]
it says no file changes i sthat right?
should it be coming from your 'master' of your fork or do you have a development branch?

**Comment by vince-roll20** [comment]
That's weird.  Maybe I needed to commit first.  I'll try again.

**Comment by vince-roll20** [comment]
Now it shows 1 file change.  I made a PR, before I submitted my commits

**Comment by vince-roll20** [comment]
Might merge this into Main as well, if you haven't already.

**Pull request merged**
